### PR TITLE
80 changing token symbol

### PR DESCRIPTION
**Pull request by MrishoLukamba**
Changing from chain_spec.rs doenst seem to be working as changes are not reflected on json file when generating it. So i have changed directly from json file, so running the node using json file will reflect the changes. At the mean time I will be investigating as to why chain_spec.rs is not doing exactly as intended

### CODE REVIEW

**Comment by ilhanu** [comment]
Hey @MrishoLukamba thanks for the PR, please remove the [blockchain database ](https://github.com/Fair-Squares/fair-squares/pull/81/files) and the .idea.xml files 

Let's wait with merging these for now, until you investigated how to integrate it in the chainspec.

**Review by ilhanu — CHANGES_REQUESTED** [review]
Please see my comments in the PR and issue

**Comment by MrishoLukamba** [comment]
Got it @ilhanu

**Comment by ilhanu** [comment]
Closing this as #97 got it covered

**Pull request closed without merging**
